import type { RuleDefinition } from "../../shared/types";

export const RULES: Record<string, RuleDefinition> = {
  "visual.gradient-fill": {
    id: "visual.gradient-fill",
    group: "visual",
    severity: "warning",
    title: "Gradient fill may change in PPTX",
    why: "Gradient fills can degrade or be converted when exported to PowerPoint.",
    fixHint: "Replace the gradient with a solid fill or rasterize the object.",
  },
  "visual.mask": {
    id: "visual.mask",
    group: "visual",
    severity: "critical",
    title: "Mask may not survive PPTX export",
    why: "Masked artwork can be flattened, cropped differently, or disappear during presentation export.",
    fixHint: "Flatten or rasterize the masked group before export.",
  },
  "visual.background-blur": {
    id: "visual.background-blur",
    group: "visual",
    severity: "warning",
    title: "Background blur may change in PPTX",
    why: "PowerPoint does not preserve Figma background blur rendering exactly.",
    fixHint: "Rasterize the blurred object or replace the blur with a static image.",
  },
  "visual.layer-blur": {
    id: "visual.layer-blur",
    group: "visual",
    severity: "warning",
    title: "Layer blur may change in PPTX",
    why: "Layer blur can rasterize or render differently after export.",
    fixHint: "Rasterize the blurred layer if visual fidelity matters.",
  },
  "visual.multiple-shadows": {
    id: "visual.multiple-shadows",
    group: "visual",
    severity: "suggestion",
    title: "Multiple shadows may not match PowerPoint",
    why: "PowerPoint shadow support is more limited than stacked Figma effects.",
    fixHint: "Simplify to one shadow or rasterize the object.",
  },
  "visual.blend-mode": {
    id: "visual.blend-mode",
    group: "visual",
    severity: "warning",
    title: "Blend mode may change in PPTX",
    why: "Non-normal blend modes depend on Figma compositing and may flatten or render differently.",
    fixHint: "Flatten the blended artwork or replace it with normal opacity/fills.",
  },
  "text.near-slide-edge": {
    id: "text.near-slide-edge",
    group: "text",
    severity: "warning",
    title: "Text is close to the slide edge",
    why: "Text near the slide edge can be clipped after font substitution or PPTX layout changes.",
    fixHint: "Move the text inward or increase the slide-safe margin.",
  },
  "text.outside-slide-bounds": {
    id: "text.outside-slide-bounds",
    group: "text",
    severity: "critical",
    title: "Text is outside the slide bounds",
    why: "Text outside the slide can be clipped or appear unexpectedly after export.",
    fixHint: "Move the text fully inside the slide bounds.",
  },
  "text.non-system-font": {
    id: "text.non-system-font",
    group: "text",
    severity: "warning",
    title: "Non-system font may be substituted",
    why: "PowerPoint will substitute fonts that are not installed on the recipient machine.",
    fixHint: "Use a safe system font or make sure the font is installed where the PPTX will be opened.",
  },
  "structure.non-16-9-slide": {
    id: "structure.non-16-9-slide",
    group: "structure",
    severity: "critical",
    title: "Slide is not 16:9",
    why: "Unexpected slide aspect ratios can create inconsistent PPTX page sizes or scaling.",
    fixHint: "Resize the slide/frame to a 16:9 size such as 1920x1080.",
  },
  "structure.object-outside-slide-bounds": {
    id: "structure.object-outside-slide-bounds",
    group: "structure",
    severity: "warning",
    title: "Object is outside the slide bounds",
    why: "Off-slide objects may be clipped, exported unexpectedly, or interfere with slide layout.",
    fixHint: "Move the object inside the slide or delete it before export.",
  },
  "structure.nested-frame": {
    id: "structure.nested-frame",
    group: "structure",
    severity: "warning",
    title: "Nested frame may not map cleanly to PPTX",
    why: "Nested frames carry Figma-specific structure that may flatten or behave unpredictably in export workflows.",
    fixHint: "Use groups or flatten the nested frame when it is only visual artwork.",
  },
};
