import type { RuleDefinition } from "../../shared/types";

export const RULES: Record<string, RuleDefinition> = {
  "visual.gradient-fill": {
    id: "visual.gradient-fill",
    group: "visual",
    severity: "warning",
    title: "Градиент может измениться в PPTX",
    why: "Градиентные заливки могут упроститься, исказиться или превратиться в сплошной цвет при экспорте в PowerPoint.",
    fixHint: "Замените градиент на сплошной цвет или растеризуйте объект перед экспортом.",
    autofix: { label: "Заменить градиент на цвет из центра" },
  },
  "visual.mask": {
    id: "visual.mask",
    group: "visual",
    severity: "critical",
    title: "Маска может некорректно перенестись в PPTX",
    why: "Объекты с масками могут сплющиться, обрезаться иначе или пропасть при экспорте презентации.",
    fixHint: "Сведите или растеризуйте группу с маской перед экспортом.",
  },
  "visual.background-blur": {
    id: "visual.background-blur",
    group: "visual",
    severity: "warning",
    title: "Background blur может измениться в PPTX",
    why: "PowerPoint не воспроизводит background blur из Figma один в один.",
    fixHint: "Растеризуйте объект с размытием или замените эффект статичным изображением.",
    autofix: { label: "Удалить background blur" },
  },
  "visual.layer-blur": {
    id: "visual.layer-blur",
    group: "visual",
    severity: "warning",
    title: "Layer blur может измениться в PPTX",
    why: "Размытие слоя может растеризоваться или выглядеть иначе после экспорта.",
    fixHint: "Растеризуйте размытый слой, если важна точная визуальная передача.",
    autofix: { label: "Удалить layer blur" },
  },
  "visual.multiple-shadows": {
    id: "visual.multiple-shadows",
    group: "visual",
    severity: "suggestion",
    title: "Несколько теней могут отличаться в PowerPoint",
    why: "Модель теней в PowerPoint ограниченнее, чем несколько наложенных эффектов в Figma.",
    fixHint: "Упростите тень до одного эффекта или растеризуйте объект.",
    autofix: { label: "Оставить одну тень" },
  },
  "visual.blend-mode": {
    id: "visual.blend-mode",
    group: "visual",
    severity: "warning",
    title: "Режим наложения может измениться в PPTX",
    why: "Нестандартные blend modes зависят от рендера Figma и могут сплющиться или выглядеть иначе.",
    fixHint: "Сведите объект с режимом наложения или замените эффект обычной прозрачностью/заливкой.",
    autofix: { label: "Сбросить режим наложения" },
  },
  "text.near-slide-edge": {
    id: "text.near-slide-edge",
    group: "text",
    severity: "warning",
    title: "Текст близко к краю слайда",
    why: "Текст рядом с краем может обрезаться после замены шрифта или изменения текстовой вёрстки в PowerPoint.",
    fixHint: "Сдвиньте текст внутрь слайда или увеличьте безопасный отступ.",
    autofix: { label: "Сдвинуть текст внутрь безопасной зоны" },
  },
  "text.outside-slide-bounds": {
    id: "text.outside-slide-bounds",
    group: "text",
    severity: "critical",
    title: "Текст выходит за границы слайда",
    why: "Текст за пределами слайда может обрезаться или неожиданно появиться после экспорта.",
    fixHint: "Полностью переместите текст внутрь границ слайда.",
    autofix: { label: "Вернуть текст в границы слайда" },
  },
  "text.non-system-font": {
    id: "text.non-system-font",
    group: "text",
    severity: "warning",
    title: "Нестандартный шрифт может замениться",
    why: "PowerPoint заменит шрифт, если он не установлен на компьютере, где откроют PPTX.",
    fixHint: "Используйте безопасный системный шрифт или убедитесь, что нужный шрифт установлен у получателя.",
    autofix: { label: "Заменить на Arial" },
  },
  "structure.non-16-9-slide": {
    id: "structure.non-16-9-slide",
    group: "structure",
    severity: "critical",
    title: "Слайд не в формате 16:9",
    why: "Неожиданное соотношение сторон может привести к разным размерам страниц или некорректному масштабированию в PPTX.",
    fixHint: "Измените размер слайда/фрейма на 16:9, например 1920x1080.",
    autofix: { label: "Привести слайд к 16:9" },
  },
  "structure.object-outside-slide-bounds": {
    id: "structure.object-outside-slide-bounds",
    group: "structure",
    severity: "warning",
    title: "Объект выходит за границы слайда",
    why: "Объекты за пределами слайда могут обрезаться, попасть в экспорт неожиданно или повлиять на layout слайда.",
    fixHint: "Переместите объект внутрь слайда или удалите его перед экспортом.",
    autofix: { label: "Вернуть объект в границы слайда" },
  },
  "structure.nested-frame": {
    id: "structure.nested-frame",
    group: "structure",
    severity: "warning",
    title: "Вложенный фрейм может нестабильно экспортироваться",
    why: "Вложенные фреймы несут Figma-специфичную структуру и могут сплющиться или повести себя непредсказуемо при экспорте.",
    fixHint: "Используйте группу или сведите вложенный фрейм, если это просто визуальный объект.",
    autofix: { label: "Заменить простой фрейм на группу" },
  },
};
